version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - local-network
  broker_app:
    image: dius/pact-broker
    ports:
      - "8080:80"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
